#!/usr/bin/env python3
"""
Generate `TRUST_CODEX/tables/EVIDENCE_INDEX.md` from the canonical structured index:
- `TRUST_CODEX/tables/evidence-index.json`

Why:
- Avoid drift between "what we say" (markdown) and "what we can hand to an assessor" (bundles + vault layout)
- Enable schema validation and CI checks
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def try_validate(schema_path: Path, instance: Any) -> list[str]:
    """
    Best-effort JSON Schema validation.
    Returns a list of validation error strings (empty if OK or if validator unavailable).
    """
    try:
        import yaml  # type: ignore  # schema is YAML
        import jsonschema  # type: ignore
    except Exception:
        return []

    try:
        schema = yaml.safe_load(schema_path.read_text(encoding="utf-8"))
        jsonschema.validate(instance=instance, schema=schema)
        return []
    except Exception as e:
        return [str(e)]


def md_escape(s: str) -> str:
    # Minimal markdown cell escaping. Keep it conservative; we primarily need to avoid newlines.
    return (s or "").replace("\n", " ").strip()


def build_markdown(index: dict[str, Any], source_rel: str) -> str:
    meta = index.get("metadata") or {}
    generated = utc_now_iso()

    out: list[str] = []
    out.append("# Evidence Index (assessment-ready)")
    out.append("")
    out.append("<!--")
    out.append("AUTOGENERATED FILE — do not edit by hand.")
    out.append(f"Source: `{source_rel}`")
    out.append(f"Generated (UTC): `{generated}`")
    out.append("-->")
    out.append("")
    out.append(
        "CMMC Level 2 assessment is **authoritative against NIST SP 800-171 Rev.2**. "
        "Rev.3 is referenced in the Codex for explanatory and forward-looking planning only."
    )
    out.append("")
    out.append("## Index metadata")
    out.append("")
    out.append(f"- **system_name**: `{meta.get('system_name','')}`")
    out.append(f"- **framework**: `{meta.get('framework','')}`")
    out.append(f"- **control_set**: `{meta.get('control_set','')}`")
    out.append(f"- **retention_baseline**: `{meta.get('retention_baseline','')}`")
    out.append("")
    out.append("## Where is the evidence?")
    out.append("")
    out.append(
        "The **Location** column below uses the **real path on the enclave VM**: **`C:\\evidence\\`**. "
        "Open the latest **`CUI-Evidence-<RunId>`** folder for artifacts and **`CUI-Validation-<RunId>`** for validation. "
        "See **docs/AUDITOR_VIEW_ON_VM.md** and **`C:\\evidence\\README-for-auditor.txt`** on the VM."
    )
    out.append("")
    out.append(
        "| Control ID (CMMC) | NIST Req | Evidence type | Artifact name | Owner role | Location | Retention | Cadence | Regeneration method |"
    )
    out.append("|---|---|---|---|---|---|---|---|---|")

    controls = index.get("controls") or []
    for c in controls:
        cid = str(c.get("control_id_cmmc") or "").strip()
        nist = str(c.get("nist_requirement_id") or "").strip()
        for ev in (c.get("evidence_items") or []):
            out.append(
                "| {cid} | {nist} | {etype} | {name} | {owner} | {loc} | {ret} | {cad} | {regen} |".format(
                    cid=md_escape(cid),
                    nist=md_escape(nist),
                    etype=md_escape(str(ev.get("evidence_type") or "")),
                    name=md_escape(str(ev.get("name") or "")),
                    owner=md_escape(str(ev.get("owner_role") or "")),
                    loc=md_escape(str(ev.get("location") or "")),
                    ret=md_escape(str(ev.get("retention") or "")),
                    cad=md_escape(str(ev.get("cadence") or "")),
                    regen=md_escape(str(ev.get("regeneration_method") or "")),
                )
            )

    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--trust-codex-dir",
        default=str(Path(__file__).resolve().parents[1]),
        help="Path to TRUST_CODEX/ directory.",
    )
    args = ap.parse_args()

    trust_codex = Path(args.trust_codex_dir).resolve()
    src = trust_codex / "tables" / "evidence-index.json"
    dst = trust_codex / "tables" / "EVIDENCE_INDEX.md"
    schema = trust_codex / "schemas" / "evidence-index.schema.yml"

    index = load_json(src)
    errors = try_validate(schema, index)
    if errors:
        msg = "\n".join(["Schema validation failed:"] + [f"- {e}" for e in errors])
        raise SystemExit(msg)

    md = build_markdown(index=index, source_rel="tables/evidence-index.json")
    dst.write_text(md, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

