#!/usr/bin/env python3
"""
Generate CONTROL_CLOSEOUT_FROM_SCTM.md from SCTM_FULL_STATUS_LIST.csv.

This is the single authoritative closeout view for assessors: control status and
basis come only from SCTM. Run in CI or after SCTM updates to prevent drift
with narrative closeout docs.
"""

from __future__ import annotations

import csv
from pathlib import Path
from datetime import datetime, timezone


def main() -> int:
    trust_codex = Path(__file__).resolve().parents[1]
    sctm_csv = trust_codex / "tables" / "SCTM_FULL_STATUS_LIST.csv"
    out_md = trust_codex / "tables" / "CONTROL_CLOSEOUT_FROM_SCTM.md"

    rows: list[dict[str, str]] = []
    with sctm_csv.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows.append({k: (v or "").strip() for k, v in row.items()})

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "# Control Closeout Status (from SCTM)",
        "",
        "**Authoritative source**: `tables/SCTM_FULL_STATUS_LIST.csv`.",
        "This document is generated from that CSV so assessors have a single, consistent view.",
        "Technical pass/fail basis for VM-evidenced controls: `validation-report.json` (control_results).",
        "",
        f"*Generated: {generated}*",
        "",
        "| Control ID | Family | Title | Classification | Pilot status | Status basis (summary) | Auditor requirement (summary) |",
        "|------------|--------|-------|----------------|--------------|------------------------|-------------------------------|",
    ]

    for r in rows:
        cid = r.get("control_id", "")
        fam = r.get("family", "")
        title = (r.get("title", "") or "").replace("|", "\\|").replace("\n", " ")
        classification = (r.get("classification", "") or "").replace("|", "\\|")
        status = (r.get("pilot_status", "") or "").replace("|", "\\|")
        basis = (r.get("pilot_status_basis", "") or "")[:120].replace("|", "\\|").replace("\n", " ")
        if len((r.get("pilot_status_basis") or "")) > 120:
            basis += "..."
        auditor_req = (r.get("auditor_requirement") or "")[:100].replace("|", "\\|").replace("\n", " ")
        if len((r.get("auditor_requirement") or "")) > 100:
            auditor_req += "..."
        lines.append(f"| {cid} | {fam} | {title} | {classification} | {status} | {basis} | {auditor_req} |")

    lines.extend(["", "---", "", "**Do not edit this file by hand.** Regenerate with:", "",
                  "```", "python TRUST_CODEX/tools/generate_closeout_from_sctm.py", "```", ""])
    out_md.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
